-- alter user table adding lastlogin, serial key for user id purpose
-- depends: 20260818_02_bccxp-account-verification-using-student-id

-- migrate: apply
ALTER TABLE users ADD COLUMN last_login TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN sequence_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE;

-- migrate: rollback
ALTER TABLE users DROP COLUMN sequence_number;
ALTER TABLE users DROP COLUMN last_login;
